server:
  port: 80
management:
  endpoints:
    web:
      base-path: /monitor #actuator的访问路径
      exposure:
        include:  "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

